blank_issues_enabled: false
contact_links:
    - name: Gladitor Network
      url: https://discord.gg/mBhawhyB2T
      about: Please ask and answer questions here.
      about: Do not create issues for these.
